services:
  - type: web
    name: lms-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8001
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: CLOUDFRONT_DOMAIN
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false

  - type: web
    name: lms-client
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npx next start -p 3001
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLIC_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
